spring:
  datasource:
    url: jdbc:mysql://192.168.240.131:3306/mybatisplus?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 1
    host: 192.168.240.131
    port: 6379
  data:
    mongodb:
      host: 192.168.240.131
      database: test
      username: test
      password: 123456
      port: 27017


