server:
  port: 8764

spring:
  application:
    name: spring-cloud-eureka-consumer
eureka:
  client:
    #表示是否将自己注册到Eureka Server，默认为true。
    registerWithEureka: true
    #表示是否从Eureka Server获取注册信息，默认为true。
    fetchRegistry: true
    server:
      waitTimeInMsWhenSyncEmpty: 0
    #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/